---

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
  when: firewalld_rule_added.changed

- name: restart mssql-server
  service:
    name: mssql-server
    state: restarted
    enabled: yes