###############################################################################
#
# Global UA-Broker Infrastructure Support Host Groups
#
###############################################################################

#- name: Setup MSSQL Database service
#  hosts: mssql-server-group
#  become: true
#  roles:
#  - { role: mssql-server-preview, tags: [ 'mssql-server-preview' ] }

- name: Setup OpenVPN server
  hosts: localhost
  connection: local
  become: true
  roles:
  - { role: openvpn,
      tags: [ 'openvpn' ],
      openvpn_server_clients: [ 'ale', 'amo', 'eni', 'jle', 'ksa', 'mni', 'nmo', 'oza', 'smo', 'dle' ],
      openvpn_revoke_these_certs: []
    }