---
# handlers file for playbooks/roles/openvpn
- name: restart openvpn
  service:
    name: "{{ openvpn_server_service_name }}"
    state: restarted
    enabled: yes

- name: restart iptables
  service:
    name: iptables
    state: restarted
    enabled: yes

- name: stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: save iptables rules
  shell: "{{ iptables_save_command }}"
  when: ansible_os_family == 'RedHat'
  listen: "save firewall"