---

- debug:
    msg: "Check to see if EULA variables are accepted"
  failed_when: (end_user_license_aggreement_consent_server != "Y" ) or (end_user_license_aggreement_consent_cli != "YES")

- name: Copy repository MSSQL Preview
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - mssql-prod.repo
    - mssql-server-preview.repo
  tags:
    - mssql-server-preview.init
    - mssql-server-preview.repos

- name: Install MSSQL preview
  yum:
    enablerepo: mssql-server-preview
    update_cache: yes
    name:
      - mssql-server
    state: present
  register: mssql_package_setup
  notify:
    - start mssql-server
  tags:
    - mssql-server-preview.init
    - mssql-server-preview.install
    - mssql-server-preview.install.server

#- name: Push MSSQL-Server config
#  template:
#    src: "{{ item }}"
#    dest: '{{ mssql_preview_config_dir }}/{{ item | basename | replace(".j2", "") }}'
#    owner: "{{ mssql_preview_user_owner }}"
#    group: "{{ mssql_preview_group_owner }}"
# with_fileglob:
#    - mssql-config/mssql.conf.j2

- name: Remove older unixODBC files if performing upgrade
  yum:
    name:
      - unixODBC-utf16
      - unixODBC-utf16-devel
    state: absent
  tags:
  - mssql-server-preview.init
  - mssql-server-preview.remove.odbc

- name: Install MSSQL-TOOLS and ODBC Drivers
  yum:
    enablerepo: mssql-prod
    name:
      - mssql-tools
      - msodbcsql17
      - unixODBC-devel
      - python-pip
      - python-devel
      - python2-pymssql
    state: present
  environment:
    ACCEPT_EULA: 'Y'
  tags:
    - mssql-server-preview.init
    - mssql-server-preview.install
    - mssql-server-preview.install.mstools

- name: Add MSSQL-Tools to .bashrc
  lineinfile:
    dest: "{{ ansible_user_dir }}/.bashrc"
    state: present
    line: 'export PATH="$PATH:/opt/mssql-tools/bin"'
  tags:
    - mssql-server-preview.init
    - mssql-server-preview.set.env

- name: Enable Firewalld service
  service:
    name: firewalld
    state: started
    enabled: yes
  tags:
    - mssql-server-preview.init
    - mssql-server-preview.enable.firewalld

- name: Add Firewalld settings
  firewalld:
    zone: public
    port: "{{ mssql_preview_tcp_port }}"
    permanent: yes
    state: enabled
  when: mssql_preview_enable_firewalld
  notify: restart firewalld
  tags:
    - mssql-server-preview.init
    - mssql-server-preview.firewalld

- name: Run MSSQL Setup script
  shell:  MSSQL_PID="{{ mssql_preview_choose_edition }}" \
          MSSQL_SA_PASSWORD="{{ mssql_preview_sa_password }}" \
          /opt/mssql/bin/mssql-conf -n setup accept-eula
  register: mssql_setup_output
  failed_when: "'Setup has completed successfully. SQL Server is now starting.' not in mssql_setup_output.stdout"
  when: mssql_package_setup.changed
  tags:
    - mssql-server-preview.init
    - mssql-server-preview.setup