---

- name: Copy repository
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - files/mssql-server-preview.repo
  tags:
    - mssql-server-preview.init
    - mssql-server-preview.repos