---

- name: Copy repository MSSQL Preview
  copy:
    src: mssql-server-preview.repo
    dest: /etc/yum.repos.d/mssql-server-preview.repo
    owner: root
    group: root
    mode: 0644
  tags:
    - mssql-server-preview.init
    - mssql-server-preview.repos